---
- name: Check migration plan for PVs
  k8s_facts:
    kind: MigPlan
    api_version: v1alpha1
    namespace: "{{ migration_namespace }}"
    name: "{{ migration_plan_name }}"
  register: mig_plan
  until: mig_plan.resources[0].get("spec", {}).get("persistentVolumes", {})
  retries: 30
  delay: 5

- name: Extract discovered PVs
  set_fact:
    pvs_discovered: "{{ item }}"
  loop: "{{ mig_plan.resources[0].spec.persistentVolumes }}"
  register: all_pvs

- name: Build list of discovered PVs 
  set_fact: 
    pv_list: "{{ all_pvs.results | map(attribute='ansible_facts.pvs_discovered.name') | list }}" 

- debug:
    msg:
    - "PVs discovered: {{ pv_list | join(' ') }}"
    - "PV action: {{ pv_action }}"
  when: pv_action == "move"

- debug:
    msg:
    - "PVs discovered: {{ pv_list | join(' ') }}"
    - "PV action: {{ pv_action }}"
    - "PV copy method: {{ pv_copy_method }}"
  when: pv_action == "copy"

- name: Update migration plan with PVs
  k8s:
    state: present
    definition: "{{ lookup('template', 'mig-plan-pv.yml.j2') }}"
