- name: Check {{ migration_sample_name }} resources status
  k8s_facts:
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors: "service={{ item }}"
  register: pod
  until: "true in (pod | json_query('resources[].status.containerStatuses[].ready'))"
  retries: 60
  delay: 10
  with_items:
   - "cart"
   - "catalogue"
   - "dispatch"
   - "mongodb"
   - "mysql"
   - "payment"
   - "rabbitmq"
   - "ratings"
   - "redis"
   - "shipping"
   - "user"
   - "web"

- name: Obtain {{ migration_sample_name }} route
  k8s_facts:
    kind: Route
    namespace: "{{ namespace }}"
    name: "front-end"
  register: robot_shop_route

- debug:
    msg: "Will check {{ migration_sample_name }} at http://{{ robot_shop_route.resources[0].spec.host }}"

- name: Verify {{ migration_sample_name }} is available
  uri:
    url: "http://{{ robot_shop_route.resources[0].spec.host }}"
    method: GET
    return_content: yes
  register: uri
  until: "'Robot' in uri.content"
  retries: 6
  delay: 10
