namespace: ocp-25021-cronjob

int_app_name: internal-cronjob
ext_app_name: external-cronjob

internal_image_name: internal-alpine
internal_image_tag: int
external_image_name: docker.io/alpine

migration_sample_name: ocp-25021-cronjob
migration_plan_name: "{{ migration_sample_name }}-migplan-{{ ansible_date_time.epoch }}"
migration_name: "{{ migration_sample_name }}-mig-{{ ansible_date_time.epoch }}"
#migration_sample_files: "{{ playbook_dir }}/mig-controller/docs/scenarios/{{ migration_sample_name }}"
with_deploy: true
with_migrate: true
with_cleanup: true
with_validate: true
pv: false
quiesce: false
