- hosts: localhost
  tasks:
    - name: Destroy all e2e tests
      k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
      with_items:
        - nginx-example
        - mysql-persistent
        - sock-shop
        - robot-shop
        - parks-app
        - mssql-example
        - mediawiki
        - ocp-25000-sets
        - ocp-25021-cronjob
        - ocp-25090-jobs
        - ocp-25212-initcont
        - ocp-24997-confmap
