- hosts: localhost
  tasks:
    - name: Destroy all e2e tests
      k8s:
        state: absent
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
      with_items:
        - nginx-example
        - mysql-persistent
        - sock-shop
        - robot-shop
        - parks-app
        - mssql-example
        - mediawiki
