- hosts: localhost
  roles:
    - { role: migration_prepare, tags: ["always"] }
    - { role: stateless, tags: ["stateless"] }
    - { role: local-images, tags: ["local-images"] }
    - { role: nfs-pv, tags: ["nfs-pv"] }
    - { role: sock-shop, tags: ["sock-shop"] }
    - { role: robot-shop, tags: ["robot-shop"] }
    - { role: parks-app, tags: ["parks-app"] }
  vars_files:
    - "{{ playbook_dir }}/config/mig_controller.yml"
    - "{{ playbook_dir }}/config/defaults.yml"
