- name: Include required vars
  include_vars:
    file: "{{ playbook_dir }}/config/mig_controller.yml"

# Source migration cluster does not need credentials isHostCluster: true
- name: Create source cluster migration definition
  k8s:
    state: present
    definition: "{{ lookup('file', 'mig-cluster-local.yml')}}"

- name: Create remote cluster definition
  k8s:
    state: present
    definition: "{{ lookup('template', 'cluster-remote.yml.j2') }}"

- name: Create SA token on destination cluster
  k8s:
    state: present
    definition: "{{ lookup('template', 'sa-secret-remote.yml.j2') }}"

- name: Create remote cluster migration defition
  k8s:
    state: present
    definition: "{{ lookup('file', 'mig-cluster-remote.yml') }}"

- name: Create migration storage creds
  k8s:
    state: present
    definition: "{{ lookup('template', 'mig-storage-creds.yml.j2') }}"

- name: Create migration storage
  k8s:
    state: present
    definition: "{{ lookup('template', 'mig-storage.yml.j2') }}"
