# k8s field_selectors cannot be used for CRs, API only supports core resources
- name: Check existing migrations for {{ migration_sample_name }}
  k8s_facts:
    api_version: v1alpha1
    kind: MigMigration
    namespace: "{{ migration_namespace }}"
  register: all_migrations

- block:

  - name: Extract discovered migrations for {{ migration_sample_name }}
    set_fact:
      migrations_to_remove: "{{ all_migrations | json_query('resources[].metadata.name') | select('match', migration_sample_name) | list }}"

  - debug:
      msg: 
        - "These existing migrations will be removed :"
        - "{{ migrations_to_remove }}"

  - name: Remove existing migrations for {{ migration_sample_name }}
    k8s:
      state: absent
      api_version: v1alpha1
      kind: MigMigration
      namespace: "{{ migration_namespace }}"
      name: "{{ item }}"
      wait: yes
    loop: "{{ migrations_to_remove }}"

  when: "migration_sample_name in (all_migrations | json_query('resources[].metadata.name') | string )"
