---
migration_sample_name: local-images
migration_plan_name: "{{ migration_sample_name }}-migplan-{{ ansible_date_time.epoch }}"
migration_name: "{{ migration_sample_name }}-mig-{{ ansible_date_time.epoch }}"
migration_sample_files: "{{ playbook_dir }}/mig-controller/docs/scenarios/{{ migration_sample_name }}"
s2i_app_location: "https://github.com/openshift/nodejs-ex"
with_deploy: true
with_migrate: true
with_cleanup: true
pv: false
quiesce: false
namespace: registry-example
