- name: Deploy {{ migration_sample_name }} mariadb
  k8s:
    state: present
    definition: "{{ lookup('template', 'mariadb.yml') }}"

- name: Check {{ migration_sample_name }} mariadb resource status
  k8s_facts:
    kind: Pod
    namespace: "{{ namespace }}"
    label_selectors: "app=mariadb"
  register: pod
  until: "true in (pod | json_query('resources[].status.containerStatuses[].ready'))"
  retries: 30
  delay: 10

# The route is necessary first to template properly mediawiki config
- name: Create {{ migration_sample_name }} route
  k8s:
    state: present
    definition: "{{ lookup('template', 'route.yml') }}"
    wait: yes

- name: Obtain {{ migration_sample_name }} route
  k8s_facts:
    kind: Route
    namespace: "{{ namespace }}"
    label_selectors: "app=mediawiki"
  register: mediawiki_route

- set_fact:
    sitename: "{{ mediawiki_route.resources[0].spec.host }}"

- name: Deploy {{ migration_sample_name }}
  k8s:
    state: present
    definition: "{{ lookup('template', 'mediawiki.yml') }}"
