- name: Check namespace
  k8s_facts:
    kind: Namespace
    name: "{{ namespace }}"
  register: ns

- name: Create namespace
  shell: "{{ oc_binary }} new-project {{ namespace }} --skip-config-write=true"
  when: ns.resources | length == 0

- name: Deploy configuration map
  k8s:
    state : present
    namespace : "{{ namespace }}"
    definition: "{{ lookup('template', 'configmap.yml.j2' )}}"

- name: Deploy redis appliation
  k8s:
    state : present
    namespace : "{{ namespace }}"
    definition: "{{ lookup('template', 'deployment-redis.yml.j2' )}}"
